# Generated by Django 5.2 on 2025-04-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
